# Book settings
title:
author: World Bank Development Data Group
logo: docs/images/logo.png

repository:
    url: https://github.com/datapartnership/hospital-accessibility
    branch: main

html:
    home_page_in_navbar: true
    extra_navbar: ""
    use_edit_page_button: true
    use_repository_button: true
    use_issues_button: true
    baseurl: https://datapartnership.org/hospital-accessibility

only_build_toc_files: true